"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
"base_path" : "."

"preserve_hierarchy": true

# This group identifies the files that should be the source for translations. If a translations key:value is used this
# indicates that translations from the idneified files will be pushed up to Crowdin.
files:
  - "source" : "app/_locales/en/messages.json"
    "languages_mapping":
      "two_letters_code":
        "zh-CN": "zh_CN"
